const recipes = [
  {
    id: 1,
    name: 'Side Dishes',
    list: [
      {
        id: 1,
        name: 'Kimchi',
        title: 'side',
        image: 'images/side/kimchi.jpg',
        ingrediants: [
          { name: 'cabbage', quantity: '1' },
          { name: 'green onion', quantity: '3' },
          { name: 'salted anchovies', quantity: '10 tbsp' },
          { name: 'soy sauce', quantity: '4 tbsp' },
          { name: 'red pepper flakes', quantity: '20 tbsp' },
          { name: 'sugar', quantity: '4 tbsp' },
          { name: 'minced garlic', quantity: '6 tbsp' },
          { name: 'corn starch syrup', quantity: '8 tbsp' }
        ],
        steps: [
          'Soak cabbage in salty water for one hour',
          'Mix sauce and add onto cut up cabbage'
        ],
      },
      {
        id: 2,
        name: 'Bibimbab sauce',
        title: 'side',
        image: 'images/side/bibimbabSauce.webp',
        ingrediants: [
          { name: 'red pepper paste', quantity: '3 tbsp' },
          { name: 'soy sauce', quantity: '1 tbsp' },
          { name: 'red pepper flakes', quantity: '1 tbsp' },
          { name: 'sugar', quantity: '4 tbsp' },
          { name: 'minced garlic', quantity: '1 tbsp' },
          { name: 'cooking wine', quantity: '3 tbsp' },
          { name: 'sugar', quantity: '2 tbsp' },
          { name: 'sesame oil', quantity: '1 tbsp' },
          { name: 'sesame seeds', quantity: '2 tbsp' },
          { name: 'peanut butter', quantity: '1 tbsp' },
          { name: 'vinegar', quantity: '1/2 tbsp' },
        ],
        steps: [
          'Mix everything together'
        ],
      },
      {
        id: 3,
        name: '마늘쭝',
        title: 'side',
        image: 'images/side/garlic.jpg',
        ingrediants: [
          { name: '마늘쭝', quantity: '2 cups' },
          { name: 'soy sauce', quantity: '4 tbsp' },
          { name: 'sugar', quantity: '3 tbsp' },
          { name: 'sesame oil', quantity: '3 tbsp' },
          { name: 'water', quantity: '1/2 cup' }
        ],
        steps: [
          'Mix everything together',
          'Boil for 30 minutes, until most of the water is evaporated',
          'Sprinkle with 울리고당 and sesame seeds'
        ],
      },
      {
        id: 4,
        name: '연근조림',
        title: 'side',
        image: 'images/side/lotusRoot.jpg',
        ingrediants: [
          { name: 'vinegar', quantity: '3 tbsp' },
          { name: 'salt', quantity: '1/2 tbsp' },
          { name: 'water', quantity: '2 cups' },
          { name: 'soy sauce', quantity: '20 tbsp' },
          { name: 'sesame seeds', quantity: '2 tbsp' },
          { name: 'sugar', quantity: '15 tbsp' },
          { name: 'corn starch syrup', quantity: '10 tbsp' }
        ],
        steps: [
          'Boil 연근 with vinegar and salt',
          'Add rest of the ingrediants, boil until water evaporates'
        ],
      },
      {
        id: 5,
        name: 'Sweet Potato Cauliflower Soup',
        title: 'side',
        image: 'images/side/sweetPotatoCauliflowerSoup.jpg',
        ingrediants: [
          { name: 'cauliflower', quantity: '1' },
          { name: 'sweet potato', quantity: '1' },
          { name: 'red bell peppers', quantity: '2' },
          { name: 'garlic', quantity: '12' },
          { name: 'curry powder', quantity: '1 tbsp' },
          { name: 'paprika', quantity: '1 tsp' },
          { name: 'cumin', quantity: '1 tsp' },
          { name: 'olive oil', quantity: '2 tbsp' },
          { name: 'coconut milk', quantity: '15 oz (one can)' },
          { name: 'vegetable broth', quantity: '2 cups' },
        ],
        steps: [
          'Heat oven to 400°',
          'Place cauliflower, sweet potato, red bell peppers and garlic in a casserole pan',
          'Drizzle with olive oil, coat with curry powder, paprika and cumin',
          'Cook for 35-40 minutes',
          'Remove pepper stems, blend together and add coconut milk and vegetable broth'
        ],
      },
      {
        id: 6,
        name: 'Sweet potato soup',
        title: 'side',
        image: 'images/side/sweetPotatoSoup.jpg',
        ingrediants: [
          { name: 'olive oil', quantity: '2 tbsp' },
          { name: 'onion', quantity: '1' },
          { name: 'sea salt', quantity: '1 tsp' },
          { name: 'pepper', quantity: '1 tsp' },
          { name: 'sweet potatoes', quantity: '3' },
          { name: 'apple', quantity: '1' },
          { name: 'garlic', quantity: '3' },
          { name: 'ginger', quantity: '1 tsp' },
          { name: 'paprika', quantity: '1/2 tsp' },
          { name: 'apple cider vinegar', quantity: '1 tsp' },
          { name: 'vegetable broth', quantity: '3 cups' },
          { name: 'coconut milk', quantity: '15 oz (1 can)' },
        ],
        steps: [
          'Dice onion and cube sweet potatoes',
          'Add onion, sea salt and pepper to a pot. Cook for 5-8 minutes',
          'Add sweet potatoes and apple, cook another 8-10 minutes',
          'Add garlic, ginger and paprika. Stir in apple cider vinegar, vegetable broth and coconut milk.',
          'Cover and simmer for 20-30 minutes',
          'Blend everything together'
        ],
      },
      {
        id: 7,
        name: 'Brocolli cheddar soup',
        title: 'side',
        image: 'images/side/brocolliCheddarSoup.jpg',
        ingrediants: [
          { name: 'butter', quantity: '2 tbsp' },
          { name: 'onion', quantity: '1/2' },
          { name: 'flour', quantity: '1/4 cups' },
          { name: 'chicken stock', quantity: '2 cups' },
          { name: 'milk', quantity: '2 cups' },
          { name: 'carrots', quantity: '1 cup' },
          { name: 'brocolli', quantity: '1 1/2 cups' }
        ],
        steps: [
          'Melt butter, dice onion and add to pot',
          'Stir flour with chicken stock, add to pot',
          'Slowly add milk to pot. Cut carrots into matchstick, dice brocolli. Add to pot',
          'Stir consistently for 15-20 minutes',
          'Add cheese on top, serve'
        ],
      },
      {
        id: 8,
        name: 'Butter corn',
        title: 'side',
        image: 'images/side/butterCorn.webp',
        ingrediants: [
          { name: 'corn', quantity: '2' },
          { name: 'salt', quantity: '1/2 tbsp' },
          { name: 'butter', quantity: '1 tbsp' }
        ],
        steps: [
          'Boil corn',
          'Cook with butter and salt until golden brown'
        ],
      },
      {
        id: 9,
        name: 'Pigs in blanket',
        title: 'side',
        image: 'images/side/pigsInBlanket.jpeg',
        ingrediants: [
          { name: 'sausages', quantity: '1 package' },
          { name: 'flour', quantity: '1 1/2 cups' },
          { name: 'baking powder', quantity: '1 1/2 tsp' },
          { name: 'sugar', quantity: '1 tsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'milk', quantity: '1/2 cup' },
          { name: 'butter', quantity: '1/3 cup' }
        ],
        steps: [
          'Preheat oven to 400°, line with parchment paper',
          'Pat sausauges dry, poke with fork.',
          'Combine everything, knead lightly and roll onto floured surface',
          'Cut into strips and wrap around sausages',
          'Bake for 15 minutes'
        ],
      },
      {
        id: 10,
        name: 'Tomato sheet pan soup',
        title: 'side',
        image: 'images/side/tomatoSoup.jpg',
        ingrediants: [
          { name: 'tomatos', quantity: '4' },
          { name: 'onion', quantity: '1' },
          { name: 'garlic', quantity: '2' },
        ],
        steps: [
          'Preheat oven to 400°',
          'Slice onion and place everything in a pan, drizzle with olive oil',
          'Cool for 30 minutes. Squeeze out garlic, blend everything together.',
          'Add salt, pepper, basil and parsley'
        ],
      },
      {
        id: 11,
        name: 'Corn soup',
        title: 'side',
        image: 'images/side/cornSoup.jpg',
        ingrediants: [
          { name: 'olive oil', quantity: '1 tbsp' },
          { name: 'potato', quantity: '1' },
          { name: 'onion', quantity: '1' },
          { name: 'garlic', quantity: '1' },
          { name: 'chicken stock', quantity: '4 cups' },
          { name: 'corn', quantity: '6 cups' },
          { name: 'parsley', quantity: '2 tbsp' }
        ],
        steps: [
          'Add olive oil, onion and potato to a pan. Cook for 6-7 minutes',
          'Add remaining ingrediants, cook for 10-15 minutes',
          'Blend everything together, add parsley on top'
        ],
      },
      {
        id: 12,
        name: 'Cheese balls',
        title: 'side',
        image: 'images/side/cheeseBalls.webp',
        ingrediants: [
          { name: 'potatos', quantity: '2' },
          { name: 'butter', quantity: '2 tbsp' },
          { name: 'parmesian cheese', quantity: '1/3 cups' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'cornstarch', quantity: '2 tbsp' },
          { name: 'egg', quantity: '1' },
          { name: 'garlic powder', quantity: '1 tbsp' },
          { name: 'parsley', quantity: '1 tbsp' },
          { name: 'cubed mozerlla', quantity: '12' }
        ],
        steps: [
          'Mash potatos, add all seasoning',
          'Roll into 12 balls, put cubed mozerella into each',
          'Fry three times until crispy'
        ],
      },
      {
        id: 13,
        name: 'Mozza sticks',
        title: 'side',
        image: 'images/side/mozzaStick.jpg',
        ingrediants: [
          { name: 'eggs', quantity: '2' },
          { name: 'water', quantity: '1/4 cup' },
          { name: 'bread crumbs', quantity: '1.5 cups' },
          { name: 'garlic salt', quantity: '1 tsp' },
          { name: 'flour', quantity: '2/3 cups' },
          { name: 'cornstarch', quantity: '1/3 cup' },
        ],
        steps: [
          'Mix bread crumbs and garlic salt in one bowl, flour and cornstarch in another, water and eggs in a third',
          'Dip mozza stick into flour, egg then breadcrumbs. Cook in oil for 30 seconds',
        ],
      },
      {
        id: 14,
        name: '장조림',
        title: 'side',
        image: 'images/side/soySauceBeef.webp',
        ingrediants: [
          { name: 'thick beef', quantity: '1 pound' },
          { name: 'soy sauce', quantity: '1/2 cup' },
          { name: 'garlic', quantity: '12 cloves' },
          { name: 'onion', quantity: '1' },
          { name: 'chili pepper', quantity: '2' }
        ],
        steps: [
          'Cover and boil beef with water for 8 minutes',
          'Rinse with cold water, cook beef with 4 cups of water over medium heat for 1 hour',
          'Add soy sauce, 1/2 cup water, garlic, onion, pepper',
          'Cook for another 20 minutes',
          'Tear beef into strips',
          'Refridgerate up to one week'
        ],
      }
    ]
  },
  {
    id: 2,
    name: 'Main Dishes',
    list: [
      {
        id: 1,
        name: 'Camelized onion pasta',
        image: 'images/main/onionPasta.webp',
        title: 'main',
        subtitle: 'Pasta',
        ingrediants: [
          { name: 'onions', quantity: '5' },
          { name: 'garlic', quantity: '12' },
          { name: 'tomato', quantity: '1' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'pepper', quantity: '1 tsp' },
          { name: 'paprika', quantity: '1 tbsp' },
          { name: 'parsley', quantity: '3 tsp' },
          { name: 'coconut milk', quantity: '1/2 cup' },
          { name: 'basil', quantity: '2 tsp' },
          { name: 'lemon juice', quantity: '2 tbsp' },
          { name: 'pasta', quantity: '3 cups' },
        ],
        steps: [
          'Preheat oven to 400°',
          'Add everything except pasta and coconute milk to a sheet pan. Drizzle with olive oil and cover with foil',
          'Cook in oven for 1 hour, tossing halfway',
          'Add pasta and coconut milk, season with more parsley and basil'
        ],
      },
      {
        id: 2,
        name: 'Spinach pasta',
        image: 'images/main/spinachPasta.jpg',
        title: 'main',
        subtitle: 'Pasta',
        ingrediants: [
          { name: 'boursin cheese garlic + herb', quantity: '1 package (5.2 oz)' },
          { name: 'cherry tomatos', quantity: '8-10 ounces' },
          { name: 'minced garlic', quantity: '2 tbsp' },
          { name: 'chives', quantity: '2 tbsp' },
          { name: 'basil', quantity: '1 cup' },
          { name: 'tortellini', quantity: '20 ounces' },
          { name: 'spinach', quantity: '2 cups' },
        ],
        steps: [
          'Preheat oven to 400°',
          'Add the cheese, tomatos and garlic to the center of a sheet pan. Drizzle olive oil, salt and pepper. Add chives and basil',
          'Bake 30-35 minutes',
          'Blend, add spinach and tortellini, mix around'
        ],
      },
      {
        id: 3,
        name: 'Protein Bars',
        image: 'images/bakery/proteinBars.jpg',
        title: 'main',
        subtitle: 'Breakfast',
        ingrediants: [
          { name: 'flour', quantity: '3/4 cup' },
          { name: 'peanut butter', quantity: '1/2 cup' },
          { name: 'maple syrup', quantity: '1/4 cup' },
          { name: 'protein powder', quantity: '2 scoops' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'dark chocolate chips', quantity: '3/4 cup' },
        ],
        steps: [
          'Mix everything togehter',
          'Put in the freezer for 1 hour',
          'Cut into squares'
        ],
      },
      {
        id: 4,
        name: 'Blueberry Muffins',
        image: 'images/bakery/blueberryMuffin.jpg',
        title: 'main',
        subtitle: 'Breakfast',
        ingrediants: [
          { name: 'flour', quantity: '1 1/2 cup' },
          { name: 'white sugar', quantity: '3/4 cup' },
          { name: 'baking powder', quantity: '2 tsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'vegetable oil', quantity: '1/3 cup' },
          { name: 'egg', quantity: '1' },
          { name: 'milk', quantity: '1/3 cup' },
          { name: 'blueberries', quantity: '1 cup' },
        ],
        steps: [
          'Preheat oven to 400°',
          'Grease 8 muffin cups',
          'Mix everything except crumble together',
          'Combine 1/2 cup sugar, 1/3 cup of flour, 1/4 cup of butter and 1 1/2 tsp of cinnamon for crumble',
          'Add to muffin tray, top each with crumble',
          'Cook 20-25 minutes'
        ],
      },
      {
        id: 5,
        name: 'Pancakes',
        image: 'images/bakery/pancakes.jpg',
        title: 'main',
        subtitle: 'Breakfast',
        ingrediants: [
          { name: 'flour', quantity: '1 1/2 cup' },
          { name: 'baking powder', quantity: '3 tsp' },
          { name: 'white sugar', quantity: '1 tbsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'milk', quantity: '1 1/4 cup' },
          { name: 'butter', quantity: '3 tbsp' },
          { name: 'egg', quantity: '1' },
        ],
        steps: [
          'Mix everything together',
          'Cook panckaes'
        ],
      },
      {
        id: 6,
        name: 'French Toast',
        image: 'images/bakery/frenchToast.jpg',
        title: 'main',
        subtitle: 'Breakfast',
        ingrediants: [
          { name: 'bread', quantity: '6 slices' },
          { name: 'milk', quantity: '1/2 cup' },
          { name: 'eggs', quantity: '2' },
          { name: 'sugar', quantity: '1 tsp' },
          { name: 'vanilla extract', quantity: '1 tsp' },
          { name: 'flour', quantity: '2 tbsp' },
        ],
        steps: [
          'Mix everything together',
          'Soak bread and cook on frying pan'
        ],
      },
      {
        id: 7,
        name: 'Lemon Muffins',
        image: 'images/main/lemonMuffins.jpg',
        title: 'main',
        subtitle: 'Breakfast',
        ingrediants: [
          { name: 'flour', quantity: '3 cup' },
          { name: 'sugar', quantity: '1 cup' },
          { name: 'poppy seeds', quantity: '2 tbsp' },
          { name: 'baking powder', quantity: '1 tbsp' },
          { name: 'baking soda', quantity: '1 tsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'yogurt', quantity: '1 1/2 cup' },
          { name: 'lemon juice', quantity: '2 tbsp' },
          { name: 'lemon zest', quantity: '2 tbsp' },
          { name: 'eggs', quantity: '2' },
          { name: 'butter', quantity: '8 tbsp' },

        ],
        steps: [
          'Preheat oven to 375°, grease 12 muffin cups',
          'Combine dry ingrediants and then fold in wet ingrediants without overmixing',
          'Put into 12 muffin cups, bake 20-25 minutes'
        ],
      },
      {
        id: 8,
        name: 'Spaghetti and Meatballs',
        image: 'images/main/spaghetti.jpg',
        title: 'main',
        subtitle: 'Western Dishes',
        ingrediants: [
          { name: 'ground beef', quantity: '1 lb' },
          { name: 'bread crumbs', quantity: '1/2 cup' },
          { name: 'milk', quantity: '1/4 cup' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'worchester sauce', quantity: '1 tsp' },
          { name: 'pepper', quantity: '1 tsp' },
          { name: 'onion', quantity: '1' },
          { name: 'egg', quantity: '1' },
        ],
        steps: [
          'Preheat oven to 400°',
          'Line pan with tin foil and spray with pam',
          'Mix everything together and line pan with 24 meatballs',
          'Cook 18-22 minutes',
          'Add can of tomatos and pasta sauce to pan',
          'Add meatballs + pasta'
        ],
      },
      {
        id: 9,
        name: 'Scalloped Potatos',
        image: 'images/main/scallopedPotatos.jpeg',
        title: 'main',
        subtitle: 'Western Dishes',
        ingrediants: [
          { name: 'potatos', quantity: '6' },
          { name: 'butter', quantity: '4 tbsp' },
          { name: 'flour', quantity: '3 tbsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'pepper', quantity: '1 tsp' },
          { name: 'milk', quantity: '2 1/2 cup' },
          { name: 'onion', quantity: '1' },
        ],
        steps: [
          'Preheat oven to 350°',
          'Cut potatos into thin slices and boil for 10-15 minutes',
          'Stir flour into butter over low heat. Dice onion and add rest of ingredaints and boil for 1 minute',
          'In a casserole pan, layer potatoes and sauce. Cover and bake for 30 minutues',
          'Uncover and cook for another 60 minutes'
        ],
      },
      {
        id: 10,
        name: 'Ribs',
        image: 'images/main/ribs.jpg',
        title: 'main',
        subtitle: 'Western Dishes',
        ingrediants: [
          { name: 'ribs', quantity: '1' },
          { name: 'apple juice', quantity: '1/2 cup' },
          { name: 'sugar', quantity: '4 tbsp' },
          { name: 'barbecue sauce', quantity: '2 tbsp' },
          { name: 'white sugar', quantity: '2 tbsp' },
          { name: 'onion powder', quantity: '1 tbsp' },
          { name: 'garlic salt', quantity: '1 tbsp' },
        ],
        steps: [
          'Preheat oven to 275°',
          'Marinade ribs, cover with foil',
          'Cook for 3 hours'
        ],
      },
      {
        id: 11,
        name: 'Japanese Curry',
        image: 'images/main/curry.jpg',
        title: 'main',
        subtitle: 'Western Dishes',
        ingrediants: [
          { name: 'cubed potatos' },
          { name: 'cubed carrots' },
          { name: 'diced onions' },
          { name: 'ginger', quantity: '1 tsp' },
          { name: 'garlic', quantity: '1 tsp' },
          { name: 'chicken thighs' },
        ],
        steps: [
          'Combine everything except curry cube',
          'Simmer uncovered for 15 minutes',
          'Add curry cube, increase heat to thicken'
        ],
      },
      {
        id: 12,
        name: '닭갈비',
        image: 'images/main/koreanChicken.jpeg',
        title: 'main',
        subtitle: 'Western Dishes',
        ingrediants: [
          { name: 'chicken thighs' },
          { name: 'onion', quantity: '1/2 cup' },
          { name: 'shredded cabbage', quantity: '1/2 cup' },
          { name: 'green onions', quantity: '2' },
          { name: 'rice cake', quantity: '1/2 cup' },
          { name: 'cubed sweet potato', quantity: '1' },
          { name: 'sugar', quantity: '3 tbsp' },
          { name: 'red pepper flakes', quantity: '4 tbsp' },
          { name: 'sesame seeds', quantity: '1 tbsp' },
          { name: 'red pepper paste', quantity: '4 tbsp' },
          { name: 'minced garlic', quantity: '2 tbsp' },
          { name: 'rice wine', quantity: '2 tbsp' },
          { name: 'soy sauce', quantity: '3 tbsp' },
          { name: '물엿', quantity: '3 tbsp' },
        ],
        steps: [
          'Mix everything together',
        ],
      },
      {
        id: 13,
        name: '만두국',
        image: 'images/main/dumplingSoup.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'dumplings', quantity: '8' },
          { name: 'egg', quantity: '1' },
          { name: 'onion', quantity: '1/2' },
          { name: 'green onion', quantity: '1' },
          { name: '국강장', quantity: '1 tbsp' },
          { name: '멸치', quantity: '4 tbsp' },
          { name: 'water', quantity: '2 cups' },
        ],
        steps: [
          'Add everything to pot and cook',
        ],
      },
      {
        id: 14,
        name: 'Kimchi Stew',
        image: 'images/main/kimchiStew.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'kimchi' },
          { name: 'pork belly' },
          { name: 'green onion', quantity: '3' },
          { name: 'onion', quantity: '1' },
          { name: 'sugar', quantity: '2 tsp' },
          { name: 'red pepper flakes', quantity: '2 tsp' },
          { name: 'red pepper paste', quantity: '1 tbsp' },
          { name: 'sesame oil', quantity: '1 tbsp' },
          { name: 'chicken stock', quantity: '2 cups' },
        ],
        steps: [
          'Add everything to a pot',
          'Cover and cook for 10 minutes on medium high heat',
          'Cover 10-15 minutes more on medium heat',
          'Add green onions and tofu'
        ],
      },
      {
        id: 15,
        name: 'Kimchi Fried Rice',
        image: 'images/main/kimchiFriedRice.jpeg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'bacon' },
          { name: 'kimchi' },
          { name: 'green onion' },
          { name: 'sesame oil', quantity: '1 tbsp' },
          { name: 'red pepper paste', quantity: '1 tbsp' },
          { name: 'sugar', quantity: '1 tbsp' },
          { name: 'soy sauce', quantity: '2 tbsp' },
        ],
        steps: [
          'Cook bacon and kimchi',
          'Add sauce and rice'
        ],
      },
      {
        id: 16,
        name: '제육볶음',
        image: 'images/main/koreanPork.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'pork' },
          { name: 'onion' },
          { name: 'carrot' },
          { name: 'minced garlic', quantity: '1 tbsp' },
          { name: 'green onion' },
          { name: 'soy sauce', quantity: '2 tbsp' },
          { name: '물엿', quantity: '1 tbsp' },
          { name: 'red pepper flakes', quantity: '2 tbsp' },
          { name: 'red pepper paste', quantity: '1 tbsp' },
          { name: 'sugar', quantity: '2 tbsp' },
        ],
        steps: [
          'Cook pork with minced garlic and soy sauce',
          'Mix in sauce and add onion and carrot',
          'Add green onion last'
        ],
      },
      {
        id: 17,
        name: 'Pineapple Chicken',
        image: 'images/main/pineappleChicken.webp',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'oil', quantity: '2 tsp' },
          { name: 'chicken thighs' },
          { name: 'red bell pepper', quantity: '1' },
          { name: 'pineapple chunks', quantity: '1 cup' },
          { name: 'minced garlic', quantity: '1 tsp' },
          { name: 'ginger', quantity: '1 tsp' },
          { name: 'pineapple juice', quantity: '3/4 cup' },
          { name: 'soy sauce', quantity: '1/4 cup' },
          { name: 'chicken broth', quantity: '1/3 cup' },
          { name: 'hoisin sauce', quantity: '1/3 cup' },
          { name: 'brown sugar', quantity: '1/4 cup' },
          { name: 'cornstarch', quantity: '2 tsp' },
          { name: 'sesame seeds', quantity: '2 tsp' },
          { name: 'green onion', quantity: '1 tbsp' },
        ],
        steps: [
          'Add chicken to pan and season, cook 6-8 minutes',
          'Add red bell pepper, pineapple chunks, ginger and minced garlic',
          'Combine pineapple juice, soy sauce, chicken broth, hoisin sauce and sugar. Add to pan',
          'Mix cornstarch with 1 tbsp of water and add to the pot. Boil to thicken',
          'Sprinkle with sesame seeds and green onion'
        ],
      },
      {
        id: 18,
        name: 'Ginger Beef',
        image: 'images/main/gingerBeef.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'steak skirt' },
          { name: 'cornstarch', quantity: '1 cup' },
          { name: 'oil', quantity: '2 tbsp' },
          { name: 'onion', quantity: '1 onion' },
          { name: 'carrots', quantity: '1 1/2 cup' },
          { name: 'minced garlic', quantity: '2 tbsp' },
          { name: 'ginger', quantity: '1 tbsp' },
          { name: 'red pepper flakes', quantity: '1/2 tsp' },
          { name: 'soy sauce', quantity: '1/2 cup' },
          { name: 'vinegar', quantity: '2 tbsp' },
          { name: 'sesame oil', quantity: '1 tbsp' },
          { name: 'pepper', quantity: '1/2 tsp' },
          { name: 'brown sugar', quantity: '1/2 cup' },
          { name: 'sesame seeds', quantity: '2 tbsp' },
          { name: 'green onions', quantity: '1/4 cup' },
        ],
        steps: [
          'Toss steak in cornstarch',
          'Add onions and oil to pan, add juliened carrots and cook for 3-4 minutes',
          'Add ginger, minced garlic and red pepper flakes',
          'Add soy sauce, vinegar, sesame oil, pepper, sugar and sesame seeds. Allow sauce to thicken.',
          'Fry beef seperately until crispy, toss beef in sauce'
        ],
      },
      {
        id: 19,
        name: 'Shrimp Pad Thai',
        image: 'images/main/padThai.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'shrimp' },
          { name: 'flat rice noodles' },
          { name: 'eggs', quantity: '2' },
          { name: 'shredded cabbage', quantity: '1 cup' },
          { name: 'green onion', quantity: '1' },
          { name: 'onion', quantity: '1/2' },
          { name: 'ketchup', quantity: '1/4 cup' },
          { name: '멸치', quantity: '2 tbsp' },
          { name: 'sugar', quantity: '2 tbsp' },
          { name: 'minced garlic', quantity: '1 tsp' },
          { name: 'peanut butter', quantity: '1 tsp' },
          { name: 'red pepper flakes', quantity: '1 tsp' },
          { name: 'soy sauce', quantity: '1 tsp' },
        ],
        steps: [
          'Boil noodles',
          'Cook everything in a pan, cook egg in the middle',
          'Add noodles'
        ],
      },
      {
        id: 20,
        name: 'Miso Ramen',
        image: 'images/main/ramen.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'minced garlic', quantity: '2 tsp' },
          { name: 'ginger', quantity: '1/2 tsp' },
          { name: 'miso', quantity: '3 tbsp' },
          { name: 'water', quantity: '3 1/2 cups' },
          { name: 'chicken stock cube', quantity: '1' },
          { name: '맛술', quantity: '1 tbsp' },
          { name: 'red pepper flakes', quantity: '1 tbsp' },
          { name: 'brown sugar', quantity: '1 tbsp' },
        ],
        steps: [
          'Marinade pork belly in soy sauce, ginger, 맛술 and sugar',
          'Mix everything together to make broth',
          'Cook noodles',
          'Combine noodles with broth, pork, soy sauce eggs, corn and seaweed'
        ],
      },
      {
        id: 21,
        name: '비빔국수',
        image: 'images/main/bibimkuksu.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'red pepper paste', quantity: '1 tbsp' },
          { name: 'soy sauce', quantity: '1 tbsp' },
          { name: 'sugar', quantity: '1 tbsp' },
          { name: 'red pepper flakes', quantity: '1/2 tbsp' },
          { name: 'sesame oil', quantity: '1 tbsp' },
        ],
        steps: [
          'Cook noodles',
          'Mix together sauce, top with seaweed and boiled egg'
        ],
      },
      {
        id: 22,
        name: 'Soy Sauce Noodles',
        image: 'images/main/soySauceNoodles.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'soy sauce', quantity: '3 tbsp' },
          { name: 'sugar', quantity: '3 tbsp' },
          { name: 'vinegar', quantity: '1 tbsp' },
          { name: 'minced garlic', quantity: '1 t sp' },
          { name: 'sesame oil', quantity: '2 tbsp' },
          { name: 'sesame seeds', quantity: '1 tbsp' },
        ],
        steps: [
          'Cook noodles',
          'Mix sauce, top with seaweed and boiled egg'
        ],
      },
      {
        id: 23,
        name: '짜장면',
        image: 'images/main/koreanNoodle.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'oil', quantity: '2 tbsp' },
          { name: 'sesame oil', quantity: '1 tbsp' },
          { name: 'pork belly (cubed)' },
          { name: 'radish (cubed)', quantity: '1 cup' },
          { name: 'potato (cubed)', quantity: '1 cup' },
          { name: 'onion (cubed)', quantity: '1 1/2 cup' },
          { name: 'black bean paste', quantity: '1/4 cup 1 tbsp' },
          { name: 'cornstarch', quantity: '2 tbsp' },
        ],
        steps: [
          'Stir fry pork for 4-5 minutes',
          'Combine cornstarch with 1/4 cup of water, 1 tsp sugar',
          'Add radish, cook for 1 minute',
          'Add potato, onion, cook for another 3 minutes',
          'Add oil and black bean paste',
          'Add 2 cups of water, simmer with lid closed for 10 minutes',
          'Stir in cornstarch and sesame oil',
          'Serve on top of noodles'
        ],
      },
      {
        id: 24,
        name: 'Lo Mein Noodles',
        image: 'images/main/onionPasta.webp',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'oil', quantity: '1.5 tbsp' },
          { name: 'garlic', quantity: '2 tbsp' },
          { name: 'onion', quantity: '1/2 cup' },
          { name: 'chicken', quantity: '1 cup' },
          { name: 'carrots', quantity: '2' },
          { name: 'bell pepper', quantity: '1' },
          { name: 'green onions', quantity: '6' },
          { name: 'lo mein noodles', quantity: '2 cups' },
          { name: 'water', quantity: '1/4 cup' },
          { name: 'cornstarch', quantity: '4 tsp' },
          { name: 'soy sauce', quantity: '4 tbsp' },
          { name: '맛술', quantity: '1 tbsp' },
          { name: 'sugar', quantity: '1 tsp' },
          { name: 'sesame oil', quantity: '1 tsp' },
        ],
        steps: [
          'Mix sauce together',
          'Cover chicken in sauce',
          'Combine everything to pan'
        ],
      },
      {
        id: 25,
        name: 'General Tso Chicken',
        image: 'images/main/tsoChicken.webp',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'egg', quantity: '1' },
          { name: 'chicken thighs' },
          { name: 'oil', quantity: '2 tbsp' },
          { name: 'green onion', quantity: '3 tbsp' },
          { name: 'garlic', quantity: '1 tbsp' },
          { name: 'orange zest', quantity: '1 tbsp' },
          { name: 'red pepper flakes', quantity: '2 tbsp' },
          { name: 'sugar', quantity: '1/2 cup' },
          { name: 'soy sauce', quantity: '1/4 cup' },
          { name: 'chicken broth', quantity: '3 tbsp' },
          { name: 'peanut oil', quantity: '2 tbsp' },
          { name: 'rice vinegar', quantity: '1 tbsp' },
          { name: 'sesame oil', quantity: '2 tsp' },
          { name: 'ginger', quantity: '1 tsp' },
          { name: 'cornstarch', quantity: '2 tsp' },
          { name: 'water', quantity: '1/4 cup' },
        ],
        steps: [
          'Toss chicken in 1 cup of cornstarch, egg, salt, pepper and 1 tsp sugar',
          'Cook in oil for 3 minutes, let cool, cook again for 2 minutes, let cool and cook again 1 minute',
          'Combine sauce, coat chicken with sauce'
        ],
      },
      {
        id: 25,
        name: 'Udon Noodles',
        image: 'images/main/usonNoodle.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'minced garlic', quantity: '1 tbsp' },
          { name: 'sesame oil', quantity: '2 tbsp'},
          { name: '멸치액젓', quantity: '1.5 tbsp' },
          { name: 'sugar', quantity: '2 tbsp' },
          { name: 'soy sauce', quantity: '1 tbsp' },
          { name: '맛술', quantity: '2 tbsp' },
        ],
        steps: [
          'Cook meat with seasoning and cook udon noodles',
          'Cut up green onion, chives and seaweed. Top the noodles with 1/4 green onion, 1/4 chives, 1/4 meat, 1/4 seeweed and an egg yolk in the middle',
          'Mix together 1 spoon of soy sauce, 며ㄹ치액젓, 올리고당, and 2 spoons of water. Pour on top.'
        ],
      },
      {
        id: 26,
        name: 'Cranberry Orange Muffins',
        image: 'images/bakery/cranberryOrangeMuffins.jpg',
        title: 'main',
        subtitle: 'Breakfast',
        ingrediants: [
          { name: 'flour', quantity: '2 cups' },
          { name: 'white sugar', quantity: '1 cup' },
          { name: 'baking powder', quantity: '2 tsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'vegetable oil', quantity: '1/2 cup' },
          { name: 'milk', quantity: '1/2 cup' },
          { name: 'egg', quantity: '2' },
          { name: 'orange juice', quantity: '1/4 cup' },
          { name: 'frozen cranberries', quantity: '1 1/2 cups' },
          { name: 'orange zest', quantity: '1 orange' },
        ],
        steps: [
          'Preheat oven to 400°',
          'Grease 12 muffin cups',
          'Mix everything together',
          'Cook 25 minutes'
        ],
      },
      {
        id: 26,
        name: '소갈비찜',
        image: 'images/main/shortBeefRibs.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: '소갈비', quantity: '900g' },
          { name: '무', quantity: '2 cups cubed' },
          { name: 'carrot', quantity: '1/2 cubed' },
          { name: 'pear', quantity: '1/2' },
          { name: 'onion', quantity: '1/2' },
          { name: 'minced garlic', quantity: '2 tbsp' },
          { name: 'soy sauce', quantity: '10 tbsp' },
          { name: '올리고당', quantity: '2 tbsp' },
          { name: '굴 소스', quantity: '1 tbsp' },
          { name: '맛술', quantity: '10 tbsp' },
          { name: 'ginger', quantity: '1/2 tbsp' },
          { name: 'sugar', quantity: '2 tbsp' },
          { name: '맛술', quantity: '5 tbsp' },
          { name: 'sesame oil', quantity: '1 tbsp' },
        ],
        steps: [
          'Soak ribs in cold water for 3 hours, changing water every hour',
          'Boil ribs in water for 3 minutes and drain',
          'Blend seasoning togther (everything except 무 and carrot)',
          'Marinate ribs and leave overnight',
          'Cube carrots, 무 and green onion',
          'Put marinated ribs with 1 cup of water and simmer',
          'When meat is cooked add vegetables, adding green onion last'
        ],
      },
      {
        id: 27,
        name: '무국',
        image: 'images/main/radishSoup.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'beef', quantity: '1' },
          { name: '무', quantity: '1/3' },
          { name: 'garlic', quantity: '1 tbsp' },
          { name: 'sesame oil', quantity: '2 tbsp' },
          { name: 'soy sauce', quantity: '3 tbsp' },
          { name: '멸치', quantity: '1 tbsp' }
        ],
        steps: [
          'Thinly chop 무',
          'Stir fry beef with sesame oil, soy sauce and garlic',
          'Add the 무',
          'Add water and 멸치, simmer beef'
        ],
      },
      {
        id: 28,
        name: '갈비탕',
        image: 'images/main/beefRibSoup.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'beef short ribs', quantity: '3 lbs' },
          { name: '무', quantity: '2 cups' },
          { name: 'onion', quantity: '1' },
          { name: 'water', quantity: '12 cups' },
          { name: 'garlic', quantity: '4' },
          { name: 'green onion', quantity: '4' }
        ],
        steps: [
          'Soak ribs in cold water',
          'Boil for 10 minutes, drain and rinse ribs',
          'Add ribs, water, 무 and onion to a pot, cook on medium for 1 hour',
          'Simmer for another hour',
          'Remove onion and strain the broth to remove fat',
          'Add ribs and 무 back to the broth, and add onion',
          'Top with cooked egg yolk strips'
        ],
      },
      {
        id: 29,
        name: '곰탕',
        image: 'images/main/beefSoup.webp',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'beef brisket', quantity: '2 lbs' },
          { name: 'beef leg bones', quantity: '2 lbs' },
          { name: '무', quantity: '2 cups' },
          { name: 'green onion', quantity: '2' },
          { name: 'onion', quantity: '1' },
          { name: 'garlic', quantity: '12' },
          { name: 'sweet potato noodles', quantity: '2 servings' },
          { name: 'fish sauce', quantity: '1 tbsp' },
          { name: 'salt', quantity: '1 tbsp' }
        ],
        steps: [
          'Soak beef in cold water for 1 hour',
          'Boil beef for 10-15 minutes',
          'Rinse beef',
          'Add beef, radish, onion, green onion, garlic to pot with 24 cups of water',
          'Cover and cook 30-35 minutes medium-high',
          'Reduce to medium heat, cook another 2 hours',
          'Throw away the vegetables, remove fat from the broth',
          'Cut beef into bite sized pieces',
          'Add fish sauce, salt and noodles to broth',
          'Top with cooked egg yolk strips and green onion'
        ],
      },
      {
        id: 30,
        name: '감자탕',
        image: 'images/main/beefBoneSoup.webp',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'pork neck bones', quantity: '3 lbs' },
          { name: 'ginger', quantity: '1 tbsp' },
          { name: '된장', quantity: '2 tbsp' },
          { name: 'onion', quantity: '1' },
          { name: 'chili pepper', quantity: '1' },
          { name: 'napa cabbage', quantity: '4 cups' },
          { name: 'potatos', quantity: '2' },
          { name: 'green onions', quantity: '4' },
          { name: 'garlic', quantity: '6' },
          { name: '고추가루', quantity: '3 tbsp' },
          { name: '고추장', quantity: '1 tbsp' },
          { name: 'fish sauce', quantity: '3 tbsp' },
          { name: 'water', quantity: '1/2 cup' }
        ],
        steps: [
          'Soak bones in cold water for 30 minutes',
          'Boil cabbage for 1 minute, then boil pork bones for 7 minutes',
          'Run cabbage and bones under cold water',
          'Add bones, ginger, 된장, onion, red pepper and 11 cups of water to a pot. Cover and cookf for 90 minutes on medium high heat',
          'Combine garlic, pepper flakes and paste, fish sauce and 1/4 cup water in a bowl',
          'Add cabbage, green onions and potato to the pot',
          'Add seasoning paste and 1/4 cup of water and cover pot',
          'Cook for another 30 mnutes over medium high heat'
        ],
      },
      {
        id: 31,
        name: '부대찌개',
        image: 'images/main/militarySoup.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'spam', quantity: '1 can' },
          { name: 'vienna squsage', quantity: '2 cans' },
          { name: 'garlic', quantity: '6' },
          { name: '고추장', quantity: '1 tbsp' },
          { name: '고추가루', quantity: '2 tbsp' },
          { name: 'soy sauce', quantity: '1 tbsp' },
          { name: 'sugar', quantity: '1 tbsp' },
          { name: 'water', quantity: '2 tbsp' },
          { name: 'pork belly', quantity: '' },
          { name: 'ramen noodles', quantity: '1 package' },
          { name: 'cabbage', quantity: '1 cup' },
          { name: 'onion', quantity: '1/2' },
          { name: 'kimchi', quantity: '1/2 cup' },
          { name: 'tofu', quantity: '' },
          { name: 'rice cakes', quantity: '' },
          { name: 'green onion', quantity: '2' },
        ],
        steps: [
          'Cook pork in water and 멸치 stock',
          'Add everything to the pot and cook',
          'Top with cheese'
        ],
      },
      {
        id: 32,
        name: '순두부찌개',
        image: 'images/main/tofuSoup.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'chicken stock', quantity: '2 cups' },
          { name: 'beef skirt', quantity: '' },
          { name: 'onion', quantity: '1' },
          { name: 'garlic', quantity: '2' },
          { name: 'green onion', quantity: '2' },
          { name: 'oil', quantity: '1 tbsp' },
          { name: 'tofu', quantity: '1/2 package' },
          { name: 'fish sauce', quantity: '2 tbsp' },
          { name: 'eggs', quantity: '2' }
        ],
        steps: [
          'Cook vegetables and beef in oil',
          'Add chicken stock and seasoning',
          'Cover for 3-4 minutes and serve'
        ],
      },
      {
        id: 33,
        name: '된장찌개',
        image: 'images/main/soybeanPasteSoup.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'thin beef', quantity: '' },
          { name: 'vegetable oil', quantity: '2 tbsp' },
          { name: 'garlic', quantity: '2' },
          { name: 'cubed potato', quantity: '1/2 cup' },
          { name: 'cubed onion', quantity: '1/2' },
          { name: '된장', quantity: '1/4 cup' },
          { name: 'tofu', quantity: '1/2 package' },
          { name: 'chili pepper', quantity: '1' },
          { name: 'green onion', quantity: '1' },
        ],
        steps: [
          'Add everything to pot with 2 cups of water, cook for 20 minutes covered'
        ],
      },
      {
        id: 34,
        name: '닭강정',
        image: 'images/main/koreanFriedChicken.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'ginger', quantity: '1 tbsp' },
          { name: 'garlic', quantity: '4' },
          { name: '고추가루', quantity: '3 tbsp' },
          { name: 'soy sauce', quantity: '1/4 cup' },
          { name: '올리고당', quantity: '1/2 cup' },
          { name: 'vinegar', quantity: '1 tbsp' },
          { name: 'mustard', quantity: '1 tbsp' },
          { name: 'brown sugar', quantity: '1 tbsp' },
          { name: 'sesame seeds', quantity: '' }
        ],
        steps: [
          'Coat chicken in corn starch',
          'Cook chicken',
          'Mix sauce together in sauce pan',
          'Coat chicken in sauce'
        ],
      },
      {
        id: 35,
        name: 'Korean Ground Beef Rice Bowl',
        image: 'images/main/koreanGroundBeef.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'ground beef', quantity: '1 lb' },
          { name: 'garlic', quantity: '5' },
          { name: 'ginger', quantity: '1 tbsp' },
          { name: 'sesame oil', quantity: '2 tsp' },
          { name: 'soy sauce', quantity: '1/2 cup' },
          { name: 'brown sugar', quantity: '1/3 cup' },
          { name: 'red pepper flakes', quantity: '1 tsp' },
          { name: 'green onion', quantity: '6' },
          { name: 'sesame seeds', quantity: '' }
        ],
        steps: [
          'Combine everything',
          'Add to rice'
        ],
      },
      {
        id: 36,
        name: 'Chicken Katsudon',
        image: 'images/main/chickenKatsudon.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'chicken', quantity: '' },
          { name: 'onion', quantity: '1/2' },
          { name: 'eggs', quantity: '2' },
          { name: 'dashi', quantity: '2/3 cup' },
          { name: '맛술', quantity: '2 tbsp' },
          { name: 'soy sauce', quantity: '2 tbsp' },
          { name: 'sugar', quantity: '1 tbsp' },
        ],
        steps: [
          'Coat chicken in flour, then egg, then panko',
          'Cook chicken in oil',
          'Add onion to pan with seasoning',
          'Once the onions are cooked, place the chicken on top and pour the slightly beaten eggs around them',
          'Cover until eggs are cooked, top with green onion'
        ],
      },
      { 
        id: 37,
        name: 'Chicken and Egg Rice Bowl',
        image: 'images/main/oyakodon.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'chicken', quantity: '' },
          { name: 'onion', quantity: '1/2' },
          { name: 'eggs', quantity: '3' },
          { name: '맛술', quantity: '1 tbsp' },
          { name: 'dashi', quantity: '1/2 cup' },
          { name: 'soy sauce', quantity: '2 tbsp' },
          { name: '맛술', quantity: '2 tbsp' },
          { name: 'sugar', quantity: '1 tbsp' },
        ],
        steps: [
          'Cut up chicken and coat with 1 tbsp of 맛술',
          'Mix seasoning together',
          'Add onion and seasoning to the pan, add chicken on top',
          'Increase the heat to medium, pour 2/3 of the slightly beaten eggs to the middle of the pan',
          'Add the remaining eggs and top with green onion'
        ],
      },
      { 
        id: 38,
        name: 'Mapo Tofu',
        image: 'images/main/mapoTofu.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'ground pork', quantity: '' },
          { name: 'garlic', quantity: '2' },
          { name: 'ginger', quantity: '1 tbsp' },
          { name: 'green onion', quantity: '2' },
          { name: 'tofu', quantity: '14 oz' },
          { name: 'spicy chili bean paste', quantity: '3 tbsp' },
          { name: 'oyster sauce', quantity: '1 tbsp' },
          { name: 'miso', quantity: '1 tbsp' },
          { name: 'soy sauce', quantity: '1 tbsp' },
          { name: '맛술', quantity: '2 tbsp' },
          { name: 'sesame oil', quantity: '1 tsp' },
          { name: 'cornstarch', quantity: '1 tsp' },
          { name: 'water', quantity: '4 tbsp' },
        ],
        steps: [
          'Cook garlic and ginger in oil',
          'Add the ground pork until cooked',
          'Add the sauce',
          'Add the tofu',
          'Add green onion'
        ],
      },
      { 
        id: 39,
        name: 'Beef and Egg Rice Bowl',
        image: 'images/main/tanindon.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'thin beef', quantity: '' },
          { name: 'onion', quantity: '1/2' },
          { name: 'eggs', quantity: '2' },
          { name: 'green onion', quantity: '1' },
          { name: 'dashi', quantity: '1/2 cup' },
          { name: 'soy sauce', quantity: '3 tbsp' },
          { name: '맛술', quantity: '3 tbsp' },
          { name: 'sugar', quantity: '2 tbsp' },
        ],
        steps: [
          'Add the sauce to a pan',
          'Add the onions and cook until soft',
          'Add the beef and cover until cooked',
          'Drizzle beaten eggs over the beef, top with green onion and cover until cooked',
        ],
      },
      { 
        id: 40,
        name: 'Beef Rice Bowl',
        image: 'images/main/gyudon.jpg',
        title: 'main',
        subtitle: 'Asian Dishes',
        ingrediants: [
          { name: 'thin beef', quantity: '' },
          { name: 'onion', quantity: '1/2' },
          { name: 'green onion', quantity: '1' },
          { name: 'dashi', quantity: '1/2 cup' },
          { name: 'soy sauce', quantity: '3 tbsp' },
          { name: '맛술', quantity: '3 tbsp' },
          { name: 'sugar', quantity: '1 tbsp' },
        ],
        steps: [
          'Add the sauce to a pan',
          'Add the onions and cook until soft',
          'Add the beef and cover until cooked',
          'Top with green onion and cover until cooked',
        ],
      },
    ]
  },
  {
    id: 3,
    name: 'Bakery',
    list: [
      {
        id: 1,
        name: 'Hamburger buns',
        image: 'images/bakery/hamburgerBuns.jpg',
        title: 'bakery',
        subtitle: 'Bread',
        ingrediants: [
          { name: 'yeast', quantity: '1 package' },
          { name: 'flour', quantity: '3 cups' },
          { name: 'warm water', quantity: '1 cup' },
          { name: 'eggs', quantity: '2' },
          { name: 'butter', quantity: '3 tbsp' },
          { name: 'white sugar', quantity: '3 tbsp' },
          { name: 'salt', quantity: '2 tsp' },
          { name: 'olive oil', quantity: '1 tsp' },
          { name: 'milk', quantity: '1 tbsp' },
          { name: 'sesame seeds', quantity: '1 tbsp' },
        ],
        steps: [
          'Combine yeast, 1/2 cup of flour and warm water. Let stand for 10-15 minutes',
          'Add 1 egg, metled butter and salt. Add 3 cups of flour.',
          'Knead dough for 5-6 minutes, add more flour if dough is sticky',
          'Form dough into circle and place into oiled bowl. Cover with foil and let rise for 2 hours',
          'Line baking sheet with parchment paper',
          'Make 8 round shapes from the dough, place on baking sheet and let rise 1 more hour',
          'Preheat oven to 375°',
          'Beat egg and milk, brush on top of each roll. Sprinkle with sesame seeds',
          'Bake 15-17 minutes',
          'Slice buns once cooled'
        ],
      },
      {
        id: 2,
        name: 'Salt bread',
        image: 'images/bakery/saltBread.jpg',
        title: 'bakery',
        subtitle: 'Bread',
        ingrediants: [
          { name: 'flour', quantity: '1 cup' },
          { name: 'sugar', quantity: '2 tbsp' },
          { name: 'butter', quantity: '6 tbsp' },
          { name: 'salt', quantity: '2 tsp' },
          { name: 'yeast', quantity: '1 package' },
          { name: 'milk', quantity: '3/4 cup' },
          { name: 'egg', quantity: '1' },
        ],
        steps: [
          'Mix together 2 tablespoons of butter, 1 teaspoon of salt and everything except the egg together, knead 10 times',
          'Let rise for 1 hour',
          'Combine 4 tablespoon of butter and 1 teaspoon of salt, freeze',
          'Role dough into 7 cone shapes, leave for 20 minutes',
          'Put teaspoon of butter mixture onto dough and roll from big end to small tip',
          'Top with egg wash and salt',
          'Cook for 15 mnutes at 400°'
        ],
      },
      {
        id: 3,
        name: 'Pizza Dough',
        image: 'images/bakery/pizza.jpeg',
        title: 'bakery',
        subtitle: 'Bread',
        ingrediants: [
          { name: 'flour', quantity: '2 cups' },
          { name: 'yeast', quantity: '1 package' },
          { name: 'sugar', quantity: '2 tsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'garlic powder', quantity: '1 tsp' },
          { name: 'basil', quantity: '1 tsp' },
          { name: 'olive oil', quantity: '2 tbsp' },
          { name: 'warm water', quantity: '3/4 cup' }
        ],
        steps: [
          'Combine 1 cup of flour, yeast, sugar, salt, garlic powder and basil. Add olive oil and warm water',
          'Gradually add another cup of flour. Form dough into a ball and place into oiled bowl. Cover and let sit for 30 minutes',
          'Preheat oven to 425°',
          'Knead dough lightly, 3-5 times and roll into a circle',
          'Transfer to parchment paper lined pizza pan, drizzle with oilve oil and poke with a fork',
          'Add toppings and bake for 15 minutes'
        ],
      },
      {
        id: 4,
        name: 'Blueberry bagels',
        image: 'images/bakery/blueberryBagels.jpg',
        title: 'bakery',
        subtitle: 'Bread',
        ingrediants: [
          { name: 'blueberries', quantity: '1 1/4 cup' },
          { name: 'warm water', quantity: '1/2 cup 1 tbsp' },
          { name: 'yeast', quantity: '1 package' },
          { name: 'sugar', quantity: '2 tbsp' },
          { name: 'flour', quantity: '3 1/2 cups' },
          { name: 'vanilla', quantity: '1 tsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'brown sugar', quantity: '2 tbsp' }
        ],
        steps: [
          'Heat blueberries on low heat, press down. Let cool',
          'Combine warm water, yeast and sugar. Let sit for 10 minutes',
          'Add flour, salt, blueberries and vanilla. Dough should be thick and sticky',
          'Knead for 10 minutes, place into oiled bowl and let sit for 30 minutes',
          'Deflate and cut into 8 pieces. Form into a ball and let rest for 5 minutes. Make a large hole into each cirlce',
          'Let rise 30 minutes on a baking sheet lined with parchment paper',
          'Preheat oven to 425°',
          'Stir brown sugar into 2 litres of boiling water',
          'Poach in water for 1 minute, flipping halfway',
          'Bake 20 minutes in the oven, slice after fully cooled'
        ],
      },
      {
        id: 5,
        name: 'Croissants',
        image: 'images/bakery/croissants.jpg',
        title: 'bakery',
        subtitle: 'Bread',
        ingrediants: [
          { name: 'warm milk', quantity: '3/4 cup' },
          { name: 'brown sugar', quantity: '2 tbsp' },
          { name: 'yeast', quantity: '1 package' },
          { name: 'salt', quantity: '1/2 tbsp' },
          { name: 'flour', quantity: '1.5 cups + 2 tbsp' },
          { name: 'butter', quantity: '3/4 cup' },
          { name: 'egg', quantity: '1' },
        ],
        steps: [
          'Combine warm milk, brown sugar and yeast. Let stand 5 minutes',
          'Add flour and salt. Knead for 5 minutes until dough is soft and smooth',
          'Place in bowl, cover and refridgerate for 1 hour',
          'Roll butter into a rectangle, place into plastic wrap and refridgerate',
          'Roll dough into a slightly bigger rectangle, place butter in the middle. Fold bottom and top to close around the butter',
          'Roll into another rectangle, fold the top and bottom again. Wrap and chill for 1 hour',
          'Repeat this 3 more times, and then refrigerate overnight',
          'Roll 1/4 inch thick rectangle, cut into 12 triangles.',
          'Roll into croissant shape, from the wide bottom to the tip',
          'Put on baking sheet and let rise for 1 hour',
          'Brush with egg wash',
          'Bake 8-12 minutes at 400°',
          'Drop heat to 375°, and bake another 8-12 minutes, until golden brown'
        ],
      },
      {
        id: 6,
        name: 'Banana Bread',
        image: 'images/bakery/bananaBread.jpg',
        title: 'bakery',
        subtitle: 'Bread',
        ingrediants: [
          { name: 'ripe bananas', quantity: '2' },
          { name: 'eggs', quantity: '2' },
          { name: 'vanilla', quantity: '1 tbsp' },
          { name: 'flour', quantity: '1 3/4 cup' },
          { name: 'cinnamon', quantity: '1 tbsp' },
          { name: 'baking soda', quantity: '1 tsp' },
          { name: 'chocolate chips', quantity: '2 tbsp' },
        ],
        steps: [
          'Mix everything together',
          'Preheat oven to 350°. Cook 30-35 minutes'
        ],
      },
      {
        id: 7,
        name: 'Raisin Tea Buns',
        image: 'images/bakery/raisinTeaBuns.jpg',
        title: 'bakery',
        subtitle: 'Desserts',
        ingrediants: [
          { name: 'flour', quantity: '3 cups' },
          { name: 'white sugar', quantity: '3/4 cups' },
          { name: 'baking powder', quantity: '4 tsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'raisins', quantity: '1 cup' },
          { name: 'butter', quantity: '3/4 cup' },
          { name: 'vanilla', quantity: '2 tsp' },
          { name: 'evaporated milk', quantity: '1 cup' },
          { name: 'lemon juice', quantity: '2 tbsp' },
        ],
        steps: [
          'Preheat oven to 375°',
          'Mix everything together',
          'Bake 16 slightly pushed down circles for 20-25 minutes',
        ],
      },
      {
        id: 8,
        name: 'Brownies',
        image: 'images/bakery/brownies.webp',
        title: 'bakery',
        subtitle: 'Desserts',
        ingrediants: [
          { name: 'butter', quantity: '1/2 cup' },
          { name: 'white sugar', quantity: '1 cup' },
          { name: 'eggs', quantity: '2' },
          { name: 'vanilla', quantity: '1 tsp' },
          { name: 'cocoa powder', quantity: '1/3 cup' },
          { name: 'flour', quantity: '1/2 cup' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'baking powder', quantity: '1 tsp' },
        ],
        steps: [
          'Preheat oven to 350°',
          'Mix everything together and cook for 25-30 minutes',
          'Make icing by combining 1 cup of powdered sugar, 1 tsp vanilla, 1 tbsp of maple syrup, 3 tbsp of cocoa powder and 3 tbsp of butter',
          'Frost brownies when cool'
        ],
      },
      {
        id: 9,
        name: 'Chocolate Chips Cookies',
        image: 'images/bakery/cookies.jpg',
        title: 'bakery',
        subtitle: 'Desserts',
        ingrediants: [
          { name: 'butter', quantity: '1 cup' },
          { name: 'white sugar', quantity: '1 cup' },
          { name: 'brown sugar', quantity: '1 cup' },
          { name: 'vanilla', quantity: '2 tsp' },
          { name: 'eggs', quantity: '2' },
          { name: 'flour', quantity: '3 cups' },
          { name: 'baking soda', quantity: '1 tsp' },
          { name: 'baking powder', quantity: '1 tsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'chocolate chips', quantity: '2 cups' },
        ],
        steps: [
          'Preheat oven to 375°',
          'Mix dry ingrediants together, then roll in wet ingrediants',
          'Roll 2-3 tablespoon balls on a baking sheet. Sprinkle with salt and press down with a fork',
          'Bake 8-10 minutes'
        ],
      },
      {
        id: 10,
        name: 'Sweet Potato Pie',
        image: 'images/bakery/sweetPotatoPie.webp',
        title: 'bakery',
        subtitle: 'Desserts',
        ingrediants: [
          { name: 'sweet potato', quantity: '3' },
          { name: 'butter', quantity: '1/2 cup' },
          { name: 'sugar', quantity: '1 cup' },
          { name: 'milk', quantity: '1/2 cup' },
          { name: 'eggs', quantity: '2' },
          { name: 'nutmeg', quantity: '1 tsp' },
          { name: 'cinnamon', quantity: '1 tsp' },
          { name: 'vanilla', quantity: '1 tsp' },
          { name: 'unbaked pie crust', quantity: '1' },
        ],
        steps: [
          'Boil the whole sweet potatoes for 40-50 minutes. Remove skin from potatos',
          'Preheat oven to 350°',
          'Mix sweet potatos with all ingredaints',
          'Pour into pie crust',
          'Cook for 55-60 minutes'
        ],
      },
      {
        id: 11,
        name: 'Chocolate Cake',
        image: 'images/bakery/chocolateCake.webp',
        title: 'bakery',
        subtitle: 'Desserts',
        ingrediants: [
          { name: 'flour', quantity: '2 cups' },
          { name: 'sugar', quantity: '2 cups' },
          { name: 'cocoa powder', quantity: '3/4 cup' },
          { name: 'baking powder', quantity: '2 tsp' },
          { name: 'baking soda', quantity: '1 1/2 tsp' },
          { name: 'salt', quantity: '1 tsp' },
          { name: 'espresso powder', quantity: '1 tsp' },
          { name: 'milk', quantity: '1 cup' },
          { name: 'oil', quantity: '1/2 cup' },
          { name: 'eggs', quantity: '2' },
          { name: 'vanilla', quantity: '2 tsp' },
          { name: 'boiling water', quantity: '1 cup' },
        ],
        steps: [
          'Preheat oven to 350°, butter 2 9-inch cake pans',
          'Combine dry ingrediants, mix in wet ingrediants',
          'Pour into cake pans and bake for 30-35 minutes',
          'Make icing by combing 1 1/2 byutter, 1 cup cocoa powder, 5 cups of powdered sugar, 1/2 cup of milk, 2 tsp vanilla and 1/2 tsp of espresso powder',
          'Ice cake when cooled'
        ],
      },
      {
        id: 12,
        name: 'Vanilla Mug Cake',
        image: 'images/bakery/mugCake.jpg',
        title: 'bakery',
        subtitle: 'Desserts',
        ingrediants: [
          { name: 'flour', quantity: '4 tablespoons' },
          { name: 'sugar', quantity: '2 tablespoons' },
          { name: 'baking powder', quantity: '1/2 teaspoon' },
          { name: 'milk', quantity: '4 tablespoons' },
          { name: 'vanilla', quantity: '1/4 teaspoon' },
          { name: 'oil', quantity: '1.5 tablespoons' },
        ],
        steps: [
          'Mix everything together',
          'Microwave for 45-60 seconds',
        ],
      },
    ]
  },
  {
    id: 4,
    name: 'Smoothies',
    list: [
      {
        id: 1,
        name: 'Green smoothie',
        image: 'images/smoothies/greenSmoothie.jpg',
        title: 'smoothies',
        subtitle: 'Healthy',
        ingrediants: [
          { name: 'spinach', quantity: '1 cup' },
          { name: 'banana', quantity: '1/2' },
          { name: 'pineapple', quantity: '1/2 cup' },
          { name: 'mango', quantity: '1/2 cup' },
          { name: 'almond milk', quantity: '1/2 cup' },
        ],
        steps: [
          'Mix everything together'
        ],
      },
      {
        id: 2,
        name: 'Berry smoothie',
        image: 'images/smoothies/berrySmoothie.jpg',
        title: 'smoothies',
        subtitle: 'Healthy',
        ingrediants: [
          { name: 'beet', quantity: '1/2' },
          { name: 'blueberries', quantity: '1/2 cup' },
          { name: 'strawberries', quantity: '1/2 cup' },
          { name: 'banana', quantity: '1/2' },
          { name: 'almond milk', quantity: '3/4 cup' },
        ],
        steps: [
          'Mix everything together'
        ],
      },
      {
        id: 3,
        name: 'Carrot cake smoothie',
        image: 'images/smoothies/carrotSmoothie.jpg',
        title: 'smoothies',
        subtitle: 'Healthy',
        ingrediants: [
          { name: 'carrots', quantity: '1/2 cup' },
          { name: 'banana', quantity: '1/2' },
          { name: 'pineapple', quantity: '1/2 cup' },
          { name: 'cinnamon', quantity: '1/2 tsp' },
          { name: 'almond milk', quantity: '3/4 cup' },
        ],
        steps: [
          'Mix everything together'
        ],
      },
    ]
  },
]

export default recipes;